version: '3.7'
services:
  ride-scheduler:
    container_name: ride-scheduler
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        REACT_APP_BACKEND_URL: "http://localhost:8080"
    volumes:
      - '/app/node_modules'
    ports:
      - 3030:80